import express from "express";
import morgan from "morgan";
import notFoundUser from "./middlewares/userMiddlewares/notFoundUser.js";
import userRouter from "./routes/userRouter.js";
import courseRouter from "./routes/courseRouter.js";
import authRouter from "./routes/authRouter.js";
import lessonRouter from "./routes/lessonRouter.js";
import enrollmentRouter from "./routes/enrollmentRouter.js";
import commentRouter from "./routes/commentRouter.js";
import errorHandler from "./middlewares/errorHandler.js";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import cors from "cors";
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const app = express();
app.use(morgan("dev"));
app.use(express.json());
app.use(cors());
app.use("/api/auth", authRouter);
app.use("/api/users", userRouter);
app.use("/api/courses", courseRouter);
app.use("/api/lessons", lessonRouter);
app.use("/api/enrollments", enrollmentRouter);
app.use("/api/comments", commentRouter);
app.use("/uploads", express.static(join(__dirname, "uploads")));
app.use(express.urlencoded({ extended: true }));
app.use("/", notFoundUser);
app.use(errorHandler);
// app.use((err, req, res, next) => {
//   console.log("ERROR:", err.message);
//   const status = err.statusCode || err.status || 500;
//   res.status(status).json({ message: err.message, errors: err.errors });
// });
export default app;
